### ISSUE TITLE
Correcting a small typo: `Last` in place of `Past`

### ISSUE THREAD

**Issue by boinst** [zVolodymyr/Harvest.Api#13]
This looks like a very small typo in [PagedListLinks.cs](https://github.com/zVolodymyr/Harvest.Api/blob/6cdd952a7345b16cfc433cb345073e1bc2797098/Harvest.Api/Models/Base/PagedListLinks.cs).

The JSON for this object returned by the Harvest API looks like this:

```
"links": {
    "first": "https://api.harvestapp.com/v2/users?is_active=true\u0026page=1\u0026per_page=100\u0026ref=first",
    "next": null,
    "previous": null,
    "last": "https://api.harvestapp.com/v2/users?is_active=true\u0026page=1\u0026per_page=100\u0026ref=last"
  }
```

I suspect that the property name should be `Last` rather than `Past`.

I tried to create a pull request, but it seems to be in my fork rather than in the upstream, sorry this is a bit new to me.

https://github.com/boinst/Harvest.Api/pull/1

**Comment by zVolodymyr** [comment]
Thanks for reporting. Fixed in version 0.0.26.
